-- ============================================================================
-- STOOP POLITICS - ASK THE STOOP (LISTENER MAILBAG)
-- Created: December 12, 2025
-- ============================================================================

-- ============================================================================
-- SECTION 1: INBOX TABLE - Listener Questions/Feedback
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."inbox" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "is_read" BOOLEAN DEFAULT FALSE,
  "replied_at" TIMESTAMPTZ,
  "admin_notes" TEXT
);

-- Index for filtering unread messages
CREATE INDEX IF NOT EXISTS "idx_inbox_unread" ON "public"."inbox"("is_read", "created_at" DESC);

-- Index for chronological listing
CREATE INDEX IF NOT EXISTS "idx_inbox_created" ON "public"."inbox"("created_at" DESC);

-- ============================================================================
-- SECTION 2: ROW LEVEL SECURITY - INBOX
-- ============================================================================

ALTER TABLE "public"."inbox" ENABLE ROW LEVEL SECURITY;

-- Policy 1: Public (anonymous) users can INSERT new messages
CREATE POLICY "inbox_public_insert" ON "public"."inbox"
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (TRUE);

-- Policy 2: Only authenticated (admin) users can SELECT/read messages
CREATE POLICY "inbox_admin_read" ON "public"."inbox"
  FOR SELECT
  TO authenticated
  USING (auth.uid() IS NOT NULL);

-- Policy 3: Only authenticated (admin) users can UPDATE messages (mark as read, add notes)
CREATE POLICY "inbox_admin_update" ON "public"."inbox"
  FOR UPDATE
  TO authenticated
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

-- Policy 4: Only authenticated (admin) users can DELETE messages
CREATE POLICY "inbox_admin_delete" ON "public"."inbox"
  FOR DELETE
  TO authenticated
  USING (auth.uid() IS NOT NULL);

-- ============================================================================
-- SECTION 3: RATE LIMITING FUNCTION (Optional Enhancement)
-- ============================================================================

-- Function to check if IP has submitted too many messages recently
-- This can be called from the app before inserting
CREATE OR REPLACE FUNCTION check_inbox_rate_limit(minutes_window INTEGER DEFAULT 5, max_messages INTEGER DEFAULT 3)
RETURNS BOOLEAN AS $$
DECLARE
  recent_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO recent_count
  FROM inbox
  WHERE created_at > NOW() - (minutes_window || ' minutes')::INTERVAL;
  
  RETURN recent_count < max_messages;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
